-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 14:49:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Odpowiedzi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Odpowiedzi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Odpowiedz_na_pytanie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uczniowie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uczniowie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pytania`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pytania` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Zawartość` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Testy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Testy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Numer_testu` VARCHAR(45) NOT NULL,
  `Pytania_id` INT NOT NULL,
  `Odpowiedzi_id` INT NOT NULL,
  `Uczniowie_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Pytania_id`, `Odpowiedzi_id`, `Uczniowie_id`),
  CONSTRAINT `fk_Testy_Pytania`
    FOREIGN KEY (`Pytania_id`)
    REFERENCES `mydb`.`Pytania` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Testy_Odpowiedzi1`
    FOREIGN KEY (`Odpowiedzi_id`)
    REFERENCES `mydb`.`Odpowiedzi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Testy_Uczniowie1`
    FOREIGN KEY (`Uczniowie_id`)
    REFERENCES `mydb`.`Uczniowie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
